### ISSUE TITLE
Uploading or editing assets causes a crash

### ISSUE THREAD

**Issue by hedgehog1029** [nodecg/dashboard#130]
When uploading new assets or editing asset names on disk (that latter part may be unsupported) NodeCG exits with the following traceback:

```
UNCAUGHT EXCEPTION! NodeCG will now exit.
TypeError: replicantsByNamespace[uploadedFile.namespace][uploadedFile.category].value.push is not a function
    at sha1File ([nodecg-root]/lib/assets/index.js:118:79)
    at ReadStream.<anonymous> ([nodecg-root]/node_modules/sha1-file/index.js:21:14)
    at ReadStream.emit (events.js:187:15)
    at ReadStream.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1098:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by Lange** [comment]
Hi @hedgehog1029,

Did you mean to open this on the main repo, https://github.com/nodecg/nodecg? This specific repo is for the standalone Electron version of the dashboard, which is not used by many people.

**Comment by hedgehog1029** [comment]
oh absolutely, my bad. I had a repo open and didn't notice which one :sweat_smile:
